export const QuestionsData = [
  {
    id: 1,
    upVotes: 4,
    downVotes: 2,
    random: 1,
    question: 'How did you do this ?',
    askedBy: 'mr-easy',
    lastActivityTime: '5 mins',
    lastActivityPerson: 'Rishab',
    tags: ['React', 'next'],
  },
  {
    id: 2,
    upVotes: 15,
    downVotes: 3,
    random: 5,
    question: 'When did you do this ?',
    askedBy: 'mr-peasy',
    lastActivityTime: '10 mins',
    lastActivityPerson: 'Anurag',
    tags: ['JS', 'TS'],
  },
  {
    id: 4,
    upVotes: 98,
    downVotes: 0,
    random: 1,
    question: 'Should we even do this ?',
    askedBy: 'mr-easy',
    lastActivityTime: '5 mins',
    lastActivityPerson: 'Rishab',
    tags: ['tailwind', 'css'],
  },
  {
    id: 5,
    upVotes: 40,
    downVotes: 13,
    random: 1,
    question: 'How did you do this ?',
    askedBy: 'mr-easy',
    lastActivityTime: '5 mins',
    lastActivityPerson: 'Rishab',
    tags: ['vue', 'angular'],
  },
  {
    id: 6,
    upVotes: 67,
    downVotes: 20,
    random: 1,
    question: 'How did you do this ?',
    askedBy: 'mr-easy',
    lastActivityTime: '5 mins',
    lastActivityPerson: 'Rishab',
    tags: ['flutter', 'handlebar'],
  },
  {
    id: 7,
    upVotes: 4,
    downVotes: 2,
    random: 1,
    question: 'How did you do this ?',
    askedBy: 'mr-easy',
    lastActivityTime: '5 mins',
    lastActivityPerson: 'Rishab',
    tags: ['tag1', 'tag2'],
  },
  {
    id: 8,
    upVotes: 4,
    downVotes: 2,
    random: 1,
    question: 'How did you do this ?',
    askedBy: 'mr-easy',
    lastActivityTime: '5 mins',
    lastActivityPerson: 'Rishab',
    tags: ['tag1', 'tag2'],
  },
  {
    id: 9,
    upVotes: 4,
    downVotes: 2,
    random: 1,
    question: 'How did you do this ?',
    askedBy: 'mr-easy',
    lastActivityTime: '5 mins',
    lastActivityPerson: 'Rishab',
    tags: ['tag1', 'tag2'],
  },
  {
    id: 10,
    upVotes: 4,
    downVotes: 2,
    random: 1,
    question: 'How did you do this ?',
    askedBy: 'mr-easy',
    lastActivityTime: '5 mins',
    lastActivityPerson: 'Rishab',
    tags: ['tag1', 'tag2'],
  },
  {
    id: 11,
    upVotes: 4,
    downVotes: 2,
    random: 1,
    question: 'How did you do this ?',
    askedBy: 'mr-easy',
    lastActivityTime: '5 mins',
    lastActivityPerson: 'Rishab',
    tags: ['tag1', 'tag2'],
  },
];
